# Generated by Django 2.2 on 2020-06-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResumes1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinfo', models.TextField(default='', max_length=4000)),
                ('cgpa', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=50)),
                ('objective', models.CharField(default='', max_length=1000)),
                ('education', models.TextField(default='', max_length=5000)),
                ('skill', models.TextField(default='', max_length=5000)),
                ('achievements', models.TextField(default='', max_length=5000)),
                ('projects', models.TextField(default='', max_length=1000)),
                ('hobbies', models.TextField(default='', max_length=4000)),
            ],
        ),
    ]
