# Generated by Django 2.2 on 2020-06-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresumes1',
            name='hobbies',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='userresumes1',
            name='pinfo',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
