# Generated by Django 2.2 on 2020-07-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20200628_0243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResumes1',
            new_name='UserResumes',
        ),
    ]
